# Generated by Django 5.2.5 on 2025-09-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0002_remove_offer_min_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
