# Generated by Django 5.2.5 on 2025-09-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0003_alter_offer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offer_images/'),
        ),
    ]
